export const CATEGORIES = [
  { id: 'heritage', label: 'Historical Places', icon: '🏛️', image: '/assets/photos/golghar.webp' },
  { id: 'modern', label: 'Modern Bihar', icon: '🏙️', image: '/assets/photos/modern_bihar.webp' },
  { id: 'food', label: 'Local Cuisines', icon: '🍲', image: '/assets/photos/local_cuisine.webp' },
  { id: 'culture', label: 'Rich Art & Culture', icon: '🎨', image: '/assets/photos/rich art culture.webp' }
];

export const IMAGES = [
  // --- UNDER 15 ---
  { id: 'mahabodhi', categoryId: 'heritage', name: 'Mahabodhi Temple', src: '/assets/under_15/MAHABODHI.webp', fact: 'The Mahabodhi Temple is a UNESCO World Heritage Site where the Buddha is said to have attained enlightenment under the sacred Bodhi Tree.' },
  { id: 'nalanda-u', categoryId: 'heritage', name: 'Nalanda University', src: '/assets/under_15/nalanda.webp', fact: 'Founded in the 5th century, Nalanda was one of the greatest centers of learning in the ancient world, attracting scholars from as far away as China and Greece.' },
  { id: 'golghar', categoryId: 'heritage', name: 'Golghar', src: '/assets/photos/golghar.webp', fact: 'Built in 1786 by Captain John Garstin, this massive beehive-shaped granary was designed to store grain for the British army after the famine of 1770.' },
  { id: 'buddha-statue', categoryId: 'heritage', name: 'Buddha Statue', src: '/assets/under_15/The-Great-Buddha-Statue.webp', fact: 'Standing 80 feet tall in Bodh Gaya, this majestic statue took seven years to complete and is made from blocks of red granite and sandstone.' },
  { id: 'rajgir-hills', categoryId: 'heritage', name: 'Rajgir Hills', src: '/assets/under_15/Rajgir_hills.webp', fact: 'Rajgir was the first capital of the Magadha empire. Its seven sacred hills are revered in Hinduism, Buddhism, and Jainism alike.' },
  { id: 'patna-metro', categoryId: 'modern', name: 'Patna Metro', src: '/assets/under_15/patna-metro.webp', fact: 'The under-construction Patna Metro will revolutionize public transit in Bihar\'s capital, easing traffic and reducing carbon emissions.' },
  { id: 'gandhi-maidan', categoryId: 'modern', name: 'Gandhi Maidan', src: '/assets/under_15/gandhi_maidan.webp', fact: 'Previously known as Patna Lawns, this historic 60-acre ground has hosted massive political rallies during and after the Indian independence movement.' },
  { id: 'ecopark', categoryId: 'modern', name: 'Eco Park', src: '/assets/under_15/eco-park.webp', fact: 'Officially Rajdhani Vatika, this urban oasis features over 3,000 varieties of flora, two lakes, and provides a green lung to modern Patna.' },
  { id: 'ganga-riverfront', categoryId: 'modern', name: 'Ganga Riverfront', src: '/assets/under_15/ganga-riverfront.webp', fact: 'A stunning modern development featuring 5 km of promenades along the sacred Ganges, connecting multiple historic ghats.' },
  { id: 'jp-path', categoryId: 'modern', name: 'JP Ganga Path', src: '/assets/under_15/jp path.webp', fact: 'Often called the "Marine Drive of Patna", this impressive 20km expressway built along the Ganges river drastically cuts down cross-city travel time.' },
  { id: 'litti-chokha', categoryId: 'food', name: 'Litti Chokha', src: '/assets/photos/local_cuisine.webp', fact: 'Bihar\'s signature soul food—roasted wheat dough balls stuffed with spiced sattu (roasted gram flour), served with smoky mashed eggplant and potato.' },
  { id: 'sattu-drink', categoryId: 'food', name: 'Sattu Drink', src: '/assets/under_15/sattu.webp', fact: 'Known as the "Desi Energy Drink", iced sattu mixed with cumin, lime, and black salt provides instant cooling and protein during Bihar\'s scorching summers.' },
  { id: 'thekua', categoryId: 'food', name: 'Thekua', src: '/assets/under_15/thekua.webp', fact: 'A revered traditional sweet made from wheat flour, ghee, and jaggery. It is the core offering (prasad) during Bihar\'s most important festival, Chhath Puja.' },
  { id: 'khaja', categoryId: 'food', name: 'Khaja', src: '/assets/under_15/khaja.webp', fact: 'This crispy, multi-layered, sugar-syrup-soaked sweet from Silao is so deeply rooted in history that it reportedly originated over 2,000 years ago.' },
  { id: 'chana-ghugni', categoryId: 'food', name: 'Chana Ghugni', src: '/assets/under_15/chana ghughni.webp', fact: 'A spicy and tangy evening street food staple made of black chickpeas simmered in a robust mustard-oil and onion gravy.' },
  { id: 'madhubani', categoryId: 'culture', name: 'Madhubani Art', src: '/assets/under_15/madhubani.webp', fact: 'Also known as Mithila painting, this ancient geometric art form uses natural dyes from plants and was originally painted on freshly plastered mud walls.' },
  { id: 'chhath', categoryId: 'culture', name: 'Chhath Puja', src: '/assets/under_15/chhath.webp', fact: 'An ancient Vedic festival honoring Surya (the Sun God) and Chhathi Maiya, unique in its rigorous fasting, river-bathing rituals, and absence of idol worship.' },
  { id: 'folk-dance', categoryId: 'culture', name: 'Bihar Folk Dance', src: '/assets/under_15/Bihar_Folk_Dance-.webp', fact: 'Dances like Jat-Jatin and Jhijhiya express the vibrant rural culture and folklore, often performed during monsoons and harvest festivals.' },
  { id: 'ganga-aarti', categoryId: 'culture', name: 'Ganga Aarti', src: '/assets/under_15/nit-ghat-ganga-aarti.webp', fact: 'A mesmerizing spiritual evening prayer held at the NIT Ghat, involving massive brass lamps, chanting, and beautiful reflections on the running river.' },
  { id: 'village-life', categoryId: 'culture', name: 'Village Life', src: '/assets/under_15/village side.webp', fact: 'Bihar\'s villages remain the heart of its culture, preserving traditional agricultural practices, tight-knit communities, and ancestral crafts.' },

  // --- 16-30 YEARS ---
  { id: 'barabar-caves', categoryId: 'heritage', name: 'Barabar Caves', src: '/assets/16-30/Barabar-Caves.webp', fact: 'Constructed during the Mauryan Empire, these are the oldest surviving rock-cut caves in India and feature glass-like highly polished interiors.' },
  { id: 'sher-shah-tomb', categoryId: 'heritage', name: 'Sher Shah Tomb', src: '/assets/under_15/sher.webp', fact: 'Located in Sasaram, this magnificent 122-foot red sandstone tomb stands in the middle of an artificial lake and is a masterpiece of Indo-Islamic architecture.' },
  { id: 'ashoka-pillar', categoryId: 'heritage', name: 'Vaishali Pillar', src: '/assets/16-30/Pillar-Ashoka-Vaishali.webp', fact: 'Unlike other Ashokan pillars bearing four lions, the Vaishali pillar is uniquely crowned by a single Asiatic lion facing north.' },
  { id: 'rajgir-ropeway', categoryId: 'heritage', name: 'Rajgir Ropeway', src: '/assets/16-30/Rajgir-Ropeway.webp', fact: 'India\'s oldest cable car system takes pilgrims on a thrilling ride up the Ratnagiri hill to reach the spectacular Vishwa Shanti Stupa.' },
  { id: 'kesaria-stupa', categoryId: 'heritage', name: 'Kesaria Stupa', src: '/assets/16-30/kesariya-stupa.webp', fact: 'Rising to over 100 feet, Kesariya is historically believed to be the largest and tallest ancient Buddhist stupa in the entire world.' },
  { id: 'iit-patna', categoryId: 'modern', name: 'IIT Patna', src: '/assets/16-30/iit patna.webp', fact: 'Established in 2008, IIT Patna has rapidly emerged as a premier institute of national importance, driving technological research in Bihar.' },
  { id: 'nit-patna', categoryId: 'modern', name: 'NIT Patna', src: '/assets/16-30/nit patna.webp', fact: 'Originally founded as the Pleaders Survey Training School in 1886, it is the sixth oldest engineering institute in India.' },
  { id: 'aiims-patna', categoryId: 'modern', name: 'AIIMS Patna', src: '/assets/16-30/AIIMS-Patna.webp', fact: 'A beacon of modern healthcare, AIIMS Patna provides advanced medical education and critical care to millions across Eastern India.' },
  { id: 'patna-museum', categoryId: 'modern', name: 'Patna Museum', src: '/assets/16-30/patna-museum.webp', fact: 'Known locally as Jadu Ghar, its legendary collection includes the 2,300-year-old Didarganj Yakshi statue and holy relics of Lord Buddha.' },
  { id: 'bihar-museum', categoryId: 'modern', name: 'Bihar Museum', src: '/assets/16-30/bihar-museum.webp', fact: 'A stunning architectural marvel of the 21st century, designed by Japan\'s Maki & Associates to showcase Bihar’s colossal history.' },
  { id: 'sattu-paratha', categoryId: 'food', name: 'Sattu Paratha', src: '/assets/16-30/sattu paratha.webp', fact: 'A beloved working-class breakfast: wholesome flatbread stuffed with roasted gram flour, carom seeds, and tangy pickle spices.' },
  { id: 'dal-pitha', categoryId: 'food', name: 'Dal Pitha', src: '/assets/16-30/Dal_Pitha.webp', fact: 'Bihar’s brilliant answer to dumplings! These healthy, steam-cooked rice flour pockets are stuffed with heavily spiced lentil paste.' },
  { id: 'champaran-mutton', categoryId: 'food', name: 'Champaran Mutton', src: '/assets/16-30/champaran mutton.webp', fact: 'Also called Ahuna Mutton, this delicacy is slow-cooked in a sealed earthen clay pot with whole spices and entire bulbs of garlic.' },
  { id: 'kadhi-bari', categoryId: 'food', name: 'Kadhi Bari', src: '/assets/16-30/kadhi bari.webp', fact: 'A comfort food staple made of pillowy gram-flour dumplings floating in a tangy yogurt and spice-infused gravy.' },
  { id: 'tilkut', categoryId: 'food', name: 'Tilkut', src: '/assets/16-30/tikut.webp', fact: 'A famous winter delicacy native to Gaya, made by vigorously pounding roasted sesame seeds and boiling jaggery together.' },
  { id: 'sonepur-mela', categoryId: 'culture', name: 'Sonepur Mela', src: '/assets/16-30/sonepur-mela.webp', fact: 'Dating back to the Mauryan empire, this vibrant month-long event is recognized as Asia\'s largest cattle and animal fair.' },
  { id: 'shrawani-mela', categoryId: 'culture', name: 'Shrawani Mela', src: '/assets/16-30/Shravani-Mela.webp', fact: 'Millions of Kanwariyas undertake an arduous barefoot trek carrying holy river water during this massive monsoon pilgrimage.' },
  { id: 'mithila-art', categoryId: 'culture', name: 'Mithila Art', src: '/assets/16-30/mithila art.webp', fact: 'Originally a localized women\'s wall art tradition, Mithila painting has exploded into an internationally recognized fine art style.' },
  { id: 'bidesia', categoryId: 'culture', name: 'Bidesia Folk', src: '/assets/16-30/bedesiya.webp', fact: 'Created by Bhikhari Thakur (the Shakespeare of Bhojpuri), this powerful folk theater addresses themes of migration and social issues.' },

  // --- 30-55 YEARS ---
  { id: 'vikramshila-u', categoryId: 'heritage', name: 'Vikramshila University', src: '/assets/30-55/vikramshila.webp', fact: 'Operating alongside Nalanda, Vikramshila was established by King Dharmapala as a premier global center for Vajrayana Buddhism.' },
  { id: 'rohtasgarh', categoryId: 'heritage', name: 'Rohtasgarh Fort', src: '/assets/30-55/Rohtasgarh-Fort.webp', fact: 'Perched strategically 1,500 feet high on the Kaimur hills, this massive fortification was considered one of the most impregnable strongholds in India.' },
  { id: 'agam-kuan', categoryId: 'heritage', name: 'Agam Kuan', src: '/assets/30-55/agam kuan.webp', fact: 'The "Unfathomable Well" dates back to Emperor Ashoka. Legend says it is bottomless and connects via underground streams to the Ganges.' },
  { id: 'pawapuri', categoryId: 'heritage', name: 'Pawapuri Temple', src: '/assets/30-55/pawapuri.webp', fact: 'Known as the "Sinless City," this gorgeous Jal Mandir (Water Temple) marks the exact spot where Lord Mahavira attained Nirvana in 527 BCE.' },
  { id: 'ajatshatru', categoryId: 'heritage', name: 'Ajatshatru Fort', src: '/assets/30-55/ajatshatru fort.webp', fact: 'Built by the mighty King Ajatshatru in the 6th century BCE to defend Pataliputra and his kingdom against the powerful Licchavi republic.' },
  { id: 'vidhan-sabha', categoryId: 'modern', name: 'Vidhan Sabha', src: '/assets/30-55/vidhan sabha.webp', fact: 'The architectural heart of Bihar’s democracy, this elegant colonial-era building has housed the State Legislative Assembly since 1920.' },
  { id: 'high-court', categoryId: 'modern', name: 'Patna High Court', src: '/assets/30-55/patna high court.webp', fact: 'Established in 1916, it is celebrated for its stunning neo-classical architecture and remains the highest seat of the state judiciary.' },
  { id: 'nalanda-new', categoryId: 'modern', name: 'Nalanda New Campus', src: '/assets/30-55/nalanda new campus.webp', fact: 'A completely net-zero green campus resurrecting the 1,500-year-old legacy of the ancient Nalanda University for the modern era.' },
  { id: 'rajendra-setu', categoryId: 'modern', name: 'Rajendra Setu', src: '/assets/30-55/rajendra-setu.webp', fact: 'Opened in 1959, this mighty double-decker bridge was the very first structure to connect the north and south banks of the Ganges.' },
  { id: 'gaya-airport', categoryId: 'modern', name: 'Gaya Airport', src: '/assets/30-55/gaya-airport.webp', fact: 'The crucial international gateway for Buddhist pilgrims from Japan, Thailand, Bhutan, and Sri Lanka visiting the holy Bodh Gaya.' },
  { id: 'makhana-kheer', categoryId: 'food', name: 'Makhana Kheer', src: '/assets/30-55/makhana kheer.webp', fact: 'Bihar completely dominates global Fox Nut (Makhana) production. This roasted makhana milk pudding is considered a royal delicacy.' },
  { id: 'bihari-kebab', categoryId: 'food', name: 'Bihari Kebab', src: '/assets/30-55/bihari kebab.webp', fact: 'Famous for its unbelievably soft texture, achieved by marinating meat with raw papaya and grilling it slowly over charcoal.' },
  { id: 'fish-curry', categoryId: 'food', name: 'Bihari Fish Curry', src: '/assets/30-55/Bihari-Style-Fish-Curry.webp', fact: 'A staple of the riverine state, this robust curry owes its distinct fiery flavor to a paste of freshly ground yellow mustard seeds.' },
  { id: 'aloo-chana', categoryId: 'food', name: 'Aloo Chana Curry', src: '/assets/30-55/aloo chana curry.webp', fact: 'A hearty, spice-laden breakfast powerhouse featuring potatoes and brown chickpeas, usually devoured with hot puffed puris.' },
  { id: 'chura-dahi', categoryId: 'food', name: 'Chura Dahi', src: '/assets/30-55/dahi-chura.webp', fact: 'The ultimate quick meal of flattened rice mixed with fresh curd and golden jaggery—especially consumed heavily on Makar Sankranti.' },
  { id: 'chanakya', categoryId: 'culture', name: 'Chanakya', src: '/assets/30-55/chanakya.webp', fact: 'The brilliant Mauryan royal advisor from Pataliputra who authored the Arthashastra, an ancient Indian masterpiece text on statecraft.' },
  { id: 'aryabhatta', categoryId: 'culture', name: 'Aryabhatta', src: '/assets/30-55/aryabhatta.webp', fact: 'The genius 5th-century mathematician from ancient Bihar who gave the world the digit "zero" and was the first to accurately calculate pi.' },
  { id: 'dashrath', categoryId: 'culture', name: 'Dashrath Manjhi', src: '/assets/30-55/dashrath_manjhi.webp', fact: 'The legendary "Mountain Man" who heroically spent 22 years single-handedly carving a road right through a mountain using only a hammer.' },
  { id: 'jain-buddha', categoryId: 'culture', name: 'Buddhism Traditions', src: '/assets/30-55/buddhism tradition.webp', fact: 'Bihar is literally named after the word "Vihara" (monastery), as the state served as the geographic cradle for both Buddhism and Jainism.' },

  // --- 55+ YEARS ---
  { id: 'lauria', categoryId: 'heritage', name: 'Lauria Nandangarh', src: '/assets/55_plus/Lauriya-Nandangarh.webp', fact: 'Features a perfectly preserved 32-foot Ashokan pillar from 244 BCE, still retaining its incredible, mirror-like Mauryan polish.' },
  { id: 'mundeshwari', categoryId: 'heritage', name: 'Mundeshwari Temple', src: '/assets/55_plus/Mundeshwari-Temple.webp', fact: 'Standing boldly on the Kaimur hills since 108 AD, it is historically considered the oldest functional Hindu temple in the world.' },
  { id: 'v-ruins', categoryId: 'heritage', name: 'Vikramshila Ruins', src: '/assets/55_plus/ruins-of-vikramshila.webp', fact: 'Excavations in Bhagalpur revealed a massive square monastery complex featuring over 100 cells, violently destroyed around 1200 CE.' },
  { id: 'layout', categoryId: 'heritage', name: 'Old Nalanda Layout', src: '/assets/55_plus/old nalanda.webp', fact: 'The ancient campus spanned 14 hectares, meticulously organized with red brick monasteries aligned directly opposite exquisite temples.' },
  { id: 'telhara', categoryId: 'heritage', name: 'Telhara University', src: '/assets/55_plus/Telhara-University.webp', fact: 'Recent excavations uncovered this forgotten university, originally mentioned by the Chinese traveler Hiuen Tsang as being even older than Nalanda!' },
  { id: 'old-patna', categoryId: 'modern', name: 'Old Patna City', src: '/assets/55_plus/old patna city.webp', fact: 'Known globally as Patna Sahib, the old city retains its medieval alleyways and is the sacred birthplace of the 10th Sikh Guru, Guru Gobind Singh.' },
  { id: 'sonpur-jnc', categoryId: 'modern', name: 'Sonpur Junction', src: '/assets/55_plus/sonepur jn.webp', fact: 'Located near the historic cattle fair, this legendary railway station features the 8th longest railway platform in the entire world.' },
  { id: 'barauni', categoryId: 'modern', name: 'Barauni Refinery', src: '/assets/55_plus/barauni refinery.webp', fact: 'Commissioned in 1964 with heavy Russian collaboration, this massive oil refinery was Bihar’s crucial leap into post-independence modern industry.' },
  { id: 'haats', categoryId: 'modern', name: 'Traditional Haats', src: '/assets/55_plus/haats.webp', fact: 'Vibrant, open-air village markets that serve not just as trade centers for farmers, but as vital social gathering events for rural communities.' },
  { id: 'malpua', categoryId: 'food', name: 'Malpua', src: '/assets/55_plus/malpua.webp', fact: 'A rich, deep-fried, fennel-flavored sweet pancake soaked in sugar syrup. It is the mandatory centerpiece dessert during Holi in Bihar.' },
  { id: 'gur-sweets', categoryId: 'food', name: 'Gur Sweets', src: '/assets/55_plus/gud sweets.webp', fact: 'Winter in Bihar signals the arrival of fresh sugarcane jaggery (Nalen Gur), used extensively to replace sugar in traditional health-boosting sweets.' },
  { id: 'khichdi', categoryId: 'food', name: 'Traditional Khichdi', src: '/assets/55_plus/khichdi.webp', fact: 'A deeply entrenched cultural tradition dictates that heavily spiced, ghee-laden Khichdi must be the staple Saturday afternoon meal in Bihar homes.' },
  { id: 'saag-bhaat', categoryId: 'food', name: 'Saag Bhaat', src: '/assets/55_plus/saag bhaat.webp', fact: 'The epitome of rustic culinary simplicity—steamed rice paired with freshly harvested, oil-tempered green leafy vegetables from local farms.' },
  { id: 'handia', categoryId: 'food', name: 'Local Drinks', src: '/assets/55_plus/local drink.webp', fact: 'Handia is an indigenous traditional rice beer brewed exclusively by local tribal groups, holding deep ceremonial and social significance.' },
  { id: 'mauryan-e', categoryId: 'culture', name: 'Mauryan Empire', src: '/assets/55_plus/mauryan empire.webp', fact: 'Ruled fiercely from Pataliputra (modern Patna), it was the first empire in history to conquer and unify almost the entire Indian subcontinent.' },
  { id: 'gupta-e', categoryId: 'culture', name: 'Gupta Empire', src: '/assets/55_plus/gupta-empire-map.webp', fact: 'Centered powerfully in Magadha (Bihar), this era is considered India’s Golden Age due strictly to monumental leaps in astronomy, math, and art.' },
  { id: 'buddhist-c', categoryId: 'culture', name: 'Buddhist Circuits', src: '/assets/55_plus/buddhist circuit.webp', fact: 'The holy footsteps of Lord Buddha map directly across Bihar—from his defining enlightenment in Bodh Gaya to his profound teachings at Vulture Peak.' }
];

export const AGE_GROUPS = {
  under_15: { id: 'under_15', size: 3, label: 'Under 15', tag: ' Young Minds', allowedImages: ['mahabodhi', 'nalanda-u', 'golghar', 'buddha-statue', 'rajgir-hills', 'patna-metro', 'gandhi-maidan', 'ecopark', 'ganga-riverfront', 'jp-path', 'litti-chokha', 'sattu-drink', 'thekua', 'khaja', 'chana-ghugni', 'madhubani', 'chhath', 'folk-dance', 'ganga-aarti', 'village-life'] },
  age_16_30: { id: 'age_16_30', size: 3, label: '16-30 Years', tag: ' Youth', allowedImages: ['barabar-caves', 'sher-shah-tomb', 'ashoka-pillar', 'rajgir-ropeway', 'kesaria-stupa', 'iit-patna', 'nit-patna', 'aiims-patna', 'patna-museum', 'bihar-museum', 'sattu-paratha', 'dal-pitha', 'champaran-mutton', 'kadhi-bari', 'tilkut', 'sonepur-mela', 'shrawani-mela', 'mithila-art', 'bhojpuri-songs', 'bidesia'] },
  age_30_55: { id: 'age_30_55', size: 3, label: '30-55 Years', tag: ' Adults', allowedImages: ['vikramshila-u', 'rohtasgarh', 'agam-kuan', 'pawapuri', 'ajatshatru', 'vidhan-sabha', 'high-court', 'nalanda-new', 'rajendra-setu', 'gaya-airport', 'makhana-kheer', 'bihari-kebab', 'fish-curry', 'aloo-chana', 'chura-dahi', 'chanakya', 'aryabhatta', 'dashrath', 'magadh', 'jain-buddha'] },
  age_55_plus: { id: 'age_55_plus', size: 3, label: '55+ Years', tag: ' Seniors', allowedImages: ['lauria', 'mundeshwari', 'v-ruins', 'layout', 'telhara', 'old-patna', 'sonpur-jnc', 'barauni', 'hajipur', 'haats', 'malpua', 'gur-sweets', 'khichdi', 'saag-bhaat', 'handia', 'angika', 'magahi', 'mauryan-e', 'gupta-e', 'buddhist-c'] }
};

export const LS_KEYS = { bestScore: 'bihar-puzzle-best-score' };
export const GAME_MODES = { SLIDER: 'slider', DRAG_DROP: 'drag_drop', JIGSAW: 'jigsaw' };
