export const CATEGORIES = [
  { id: 'heritage', label: 'Historical Places', icon: '🏛️', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Buddha_Statue_in_Bodh_Gaya.jpg', desc: 'Ancient wonders and monuments' },
  { id: 'modern', label: 'Modern Bihar', icon: '🏙️', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Bihar_Vidhan_Sabha_Building.jpg', desc: 'Contemporary developments' },
  { id: 'food', label: 'Local Cuisines', icon: '🍲', image: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Sattu_Paratha_with_Chokha.jpg', desc: 'Authentic flavors and dishes' },
  { id: 'culture', label: 'Rich Art & Culture', icon: '🎨', image: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Bihar_Folk_Dance-.jpg', desc: 'Traditions and artistic heritage' }
];

export const IMAGES = [
  // --- UNDER 15 ---
  { id: 'mahabodhi', categoryId: 'heritage', name: 'Mahabodhi Temple', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Buddha_Statue_in_Bodh_Gaya.jpg', fact: 'Place where Buddha attained enlightenment.' },
  { id: 'nalanda-u', categoryId: 'heritage', name: 'Nalanda University', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Telhara_Ancient_University_Excavation_Site.jpg', fact: 'Ancient world-renowned learning center.' },
  { id: 'golghar', categoryId: 'heritage', name: 'Golghar', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Gandhi_maidan_patna.jpg', fact: 'Massive beehive granary in Patna.' },
  { id: 'buddha-statue', categoryId: 'heritage', name: 'Buddha Statue', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Buddha_Statue_in_Bodh_Gaya.jpg', fact: '80-foot Bodh Gaya landmark.' },
  { id: 'rajgir-hills', categoryId: 'heritage', name: 'Rajgir Hills', src: 'https://picxy.com/images/high_res_files/stock-photo/IA282723-1579246101.jpg', fact: 'Sacred hills of Rajgir.' },
  { id: 'patna-metro', categoryId: 'modern', name: 'Patna Metro', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/IIT_Patna_Campus.jpg/1280px-IIT_Patna_Campus.jpg', fact: 'Modern transit project of Bihar.' },
  { id: 'gandhi-maidan', categoryId: 'modern', name: 'Gandhi Maidan', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Gandhi_maidan_patna.jpg', fact: 'Epicenter of events in Patna.' },
  { id: 'ecopark', categoryId: 'modern', name: 'Eco Park', src: 'https://imgs.search.brave.com/v-ycMUUAfMNKg9-58Zx9v1vEbN7ytCqiDhx6x4OPVG4/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3Bob3RvLW8v/MDgvOWQvNmMvYjgv/ZWNvLXBhcmstcmFq/ZGhhbmktdmF0aWth/LmpwZw', fact: ' Rajdhani Vatika urban oasis.' },
  { id: 'ganga-riverfront', categoryId: 'modern', name: 'Ganga Riverfront', src: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Ganga_Aarti_at_Patna.jpg', fact: 'Developing bank of sacred Ganges.' },
  { id: 'jp-path', categoryId: 'modern', name: 'JP Ganga Path', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rajendra_Setu.jpg/1280px-Rajendra_Setu.jpg', fact: 'Marine Drive of Bihar.' },
  { id: 'litti-chokha', categoryId: 'food', name: 'Litti Chokha', src: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Sattu_Paratha_with_Chokha.jpg', fact: 'Signature Bihar soul food.' },
  { id: 'sattu-drink', categoryId: 'food', name: 'Sattu Drink', src: 'https://imgs.search.brave.com/6qxhZBEGvpA7KlMwTmbeO9UFKlgfGp8QLzjxpvJBwXY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/c2h1dHRlcnN0b2Nr/LmNvbS9pbWFnZS1w/aG90by9zYXR0dS1z/dW1tZXItZHJpbmst/cHJlcGFyZWQtYnkt/MjYwbnctMTM2NTI5/MDQ5NS5qcGc', fact: 'Protein-rich desi energy drink.' },
  { id: 'thekua', categoryId: 'food', name: 'Thekua', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Malpua.jpg/1280px-Malpua.jpg', fact: 'Traditional Chhath Puja cookie.' },
  { id: 'khaja', categoryId: 'food', name: 'Khaja', src: 'https://imgs.search.brave.com/sey1lLs1sae3PG7hAQWmUuM64TRHUYcjBYdLS81IB5g/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly81Lmlt/aW1nLmNvbS9kYXRh/NS9BTkRST0lEL0Rl/ZmF1bHQvMjAyMS8x/L0tCL1VML01ZLzIz/MTI4Njg2L3Byb2Qt/MjAyMTAxMDYtMTI1/NzQwNDE3NzA4NjIy/MTgxOTI5NzAxNC1q/cGctNTAweDUwMC5q/cGc', fact: 'Crispy layered sweet from Silao.' },
  { id: 'chana-ghugni', categoryId: 'food', name: 'Chana Ghugni', src: 'https://imgs.search.brave.com/Cf8e3M1xmkKkRdVM-1Wu9oe9A6XZLZDu98qocaf2SBU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/dmVnYW5yaWNoYS5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjMvMDUvS2FsYS1D/aGFuYS1HaHVnbmkt/NzY0NC0zMDB4MzAw/LmpwZw', fact: 'Spicy chickpea street delicacy.' },
  { id: 'madhubani', categoryId: 'culture', name: 'Madhubani Art', src: 'https://imgs.search.brave.com/TzrHJ_bcPDi2Oe7kAkF3lwMmbNKdJrRHztzqZ0uCtfc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTQx/OTU2MjE5Ni9waG90/by90cmFkaXRpb25h/bC1tYWRodWJhbmkt/cGFudGluZy1vZi1s/YWRpZXMuanBnP3M9/NjEyeDYxMiZ3PTAm/az0yMCZjPXdwU0hp/LVNqY0lWeFoxQlh4/a1hlOXMyb0dUYmp2/WVExNnlSVmNxb0RI/X0E9', fact: 'Mithila colorful geometric art.' },
  { id: 'chhath', categoryId: 'culture', name: 'Chhath Puja', src: 'https://imgs.search.brave.com/zcPc4Ucz2X3LGlBqwghZEdA1NHw_XxMl9g7iksch8Hs/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90My5m/dGNkbi5uZXQvanBn/LzE4LzcxLzE1Lzk0/LzM2MF9GXzE4NzEx/NTk0MTFfSzZzbWlY/bUdjMlRvbjF4TW1l/NlgxUVlwSkN0RzRv/MEouanBn', fact: 'Ancient Vedic Sun festival.' },
  { id: 'folk-dance', categoryId: 'culture', name: 'Bihar Folk Dance', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Bihar_Focal_Dance-.jpg', fact: 'Rural vibrant dance traditions.' },
  { id: 'ganga-aarti', categoryId: 'culture', name: 'Ganga Aarti', src: 'https://upload.wikimedia.org/wikipedia/commons/a/ac/Ganga_Aarti_at_Patna.jpg', fact: 'Spiritual evening prayer on River banks.' },
  { id: 'village-life', categoryId: 'culture', name: 'Village Life', src: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rural_Bihar.jpg', fact: 'Rooted and simple Bihar lifestyle.' },

  // --- 16-30 YEARS ---
  { id: 'barabar-caves', categoryId: 'heritage', name: 'Barabar Caves', src: 'https://imgs.search.brave.com/gNS9wl8pwN04xRxHVgrXVTmOmZo1lHt2F8RRDNOhxHY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/Z29zYWhpbi5jb20v/Z28vcC9mL3QxLzE1/NDYxODQ5NDRfYmFy/YWJhci1jYXZlcy1z/dWx0YW5wdXIyLmpw/Zw', fact: 'Ancient Maurya rock-cut caves.' },
  { id: 'sher-shah-tomb', categoryId: 'heritage', name: 'Sher Shah Tomb', src: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Ashoka%27s_Pillar%2C_Vaishali.jpg', fact: 'Lake-monument of Sasaram.' },
  { id: 'ashoka-pillar', categoryId: 'heritage', name: 'Vaishali Pillar', src: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Ashoka%27s_Pillar%2C_Vaishali.jpg', fact: 'Emperor Ashoka\'s lion pillar.' },
  { id: 'rajgir-ropeway', categoryId: 'heritage', name: 'Rajgir Ropeway', src: 'https://picxy.com/images/high_res_files/stock-photo/IA282723-1579246101.jpg', fact: 'India\'s oldest cable car.' },
  { id: 'kesaria-stupa', categoryId: 'heritage', name: 'Kesaria Stupa', src: 'https://imgs.search.brave.com/Fgv7Xrw8mXOJlGuSJ7UC-cu_x3dosJdra0Y_Jyw0qRY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9wd29u/bHlpYXMuY29tL3dw/LWNvbnRlbnQvdXBs/b2Fkcy8yMDI0LzA0/L3VudGl0bGVkLTIw/MjQtMDQtMjB0MTIx/NjI5MTU1LTEtNjYy/MzhkYjlhYTJhOS53/ZWJw', fact: 'World\'s mammoth-sized stupa.' },
  { id: 'iit-patna', categoryId: 'modern', name: 'IIT Patna', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/IIT_Patna_Campus.jpg/1280px-IIT_Patna_Campus.jpg', fact: 'National institute of tech.' },
  { id: 'nit-patna', categoryId: 'modern', name: 'NIT Patna', src: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Patna_Museum_%28cropped%29.jpg', fact: 'Historic technical college.' },
  { id: 'aiims-patna', categoryId: 'modern', name: 'AIIMS Patna', src: 'https://imgs.search.brave.com/HEUILIt4W5_VpzcvTyCfd1IE0fJsgEzwBbOeCaxu41U/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9ibG9n/LnJtZ29lLm9yZy93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8w/Ny9BSUlNUy1QYXRu/YS0xLndlYnA', fact: 'Top medical hub of the state.' },
  { id: 'patna-museum', categoryId: 'modern', name: 'Patna Museum', src: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Patna_Museum_%28cropped%29.jpg', fact: 'Artifacts of ancient history.' },
  { id: 'bihar-museum', categoryId: 'modern', name: 'Bihar Museum', src: 'https://imgs.search.brave.com/J04teGGNvPqJ1v7x5Pp--0ELKHdzhq743lOJpfjPDGk/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zd2Fy/YWp5YS5ndW1sZXQu/aW8vc3dhcmFqeWEv/MjAyNS0wNC0yMy9z/ZGQ1bm85bS9pbWFn/ZS0xMjAweDgwMC5q/cGc_dz0xMjIwJnE9/MTAwJmNvbXByZXNz/PXRydWUmZm9ybWF0/PWF1dG8', fact: 'State-of-the-art museum.' },
  { id: 'sattu-paratha', categoryId: 'food', name: 'Sattu Paratha', src: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Sattu_Paratha_with_Chokha.jpg', fact: 'Lentil-stuffed nutritious flatbread.' },
  { id: 'dal-pitha', categoryId: 'food', name: 'Dal Pitha', src: 'https://gastronomesjournal.com/wp-content/uploads/2017/01/Dal-Pitha-Bihar-Style-5.jpg', fact: 'Nutritious steamed dumplings.' },
  { id: 'champaran-mutton', categoryId: 'food', name: 'Champaran Mutton', src: 'https://thumbs.dreamstime.com/b/champaran-mutton-handi-ahuna-popular-dish-bihar-state-india-253105610.jpg', fact: 'Handi-cooked spicy mutton.' },
  { id: 'kadhi-bari', categoryId: 'food', name: 'Kadhi Bari', src: 'https://imgs.search.brave.com/FjyE0J4Kr8Oq_trm3FdKPms2k8Nuv8O5To8wdA2xsWo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9saXR0/aS1jaG9raGEtbGl0/aS1jaG9rYS1zdHVm/ZmVkLWNoYW5hLXNh/dHR1LWluZGlhbi1k/aXNoLWJpaGFyLXNl/cnZlZC1naW5nZXIt/Z2FybGljLW1pbnQt/Y2h1dG5leS1iYWlu/Z2FuLTIxNjg5MjM4/OS5qcGc', fact: 'Gram flour dumplings in gravy.' },
  { id: 'tilkut', categoryId: 'food', name: 'Tilkut', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Malpua.jpg/1280px-Malpua.jpg', fact: 'Sesame and jaggery winter snack.' },
  { id: 'sonepur-mela', categoryId: 'culture', name: 'Sonepur Mela', src: 'https://thumbs.dreamstime.com/b/sonepur-mela-bihar-india-november-horse-racing-asia-s-largest-cattle-fair-133596767.jpg', fact: 'Grand historic cattle fair.' },
  { id: 'shrawani-mela', categoryId: 'culture', name: 'Shrawani Mela', src: 'https://www.gettyimages.co.uk/gi-resources/images/Homepage/Hero/UK/Hero-Images-Sultanganj-Bihar-India-August-18-2010.jpg', fact: 'Longest pilgrimage route.' },
  { id: 'mithila-art', categoryId: 'culture', name: 'Mithila Art', src: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Didarganj_Yakshi_Patna_Museum.jpg', fact: 'Heritage foundation of Madhubani.' },
  { id: 'bhojpuri-songs', categoryId: 'culture', name: 'Bhojpuri Songs', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Bihar_Focal_Dance-.jpg', fact: 'Soulful folk melodies of Bihar.' },
  { id: 'bidesia', categoryId: 'culture', name: 'Bidesia Folk', src: 'https://imgs.search.brave.com/xFYt4-1aajk2ojeSZCib_vO0cJ-5jb-nVOdsoJld4p8/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9jYWxl/aWRvc2NvcGUuaW4v/d3AtY29udGVudC91/cGxvYWRzLzIwMjMv/MDEvRm9say1EYW5j/ZXMtb2YtQmloYXIt/QmlkZXNpYS1EYW5j/ZS0uanBn', fact: 'Theatrical folk play form.' },

  // --- 30-55 YEARS ---
  { id: 'vikramshila-u', categoryId: 'heritage', name: 'Vikramshila University', src: 'https://imgs.search.brave.com/ooqCkiQL_csUSkctKBeRQm6F50ADCTg-4rsxa9bEJ7s/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oaXN0/b3JpZmllZC5pbi93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8w/NS9TY3JlZW5zaG90/XzIwMjAwNTMxLTE1/MzUzNi03MjB4NTYw/LmpwZw', fact: 'Ancient Buddhist university ruins.' },
  { id: 'rohtasgarh', categoryId: 'heritage', name: 'Rohtasgarh Fort', src: 'https://imgs.search.brave.com/2Hh7QJZfF7osTlyGOCtORHMxYsPL6RnTW7yiyDErA2E/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMudGVsZWdyYXBo/aW5kaWEuY29tL3Rl/bGVncmFwaC8yMDIz/L05vdi8xNjk5MTQz/OTUwX2ZvcnQuZ2lm.jpeg', fact: 'Ancient and powerful hill fort.' },
  { id: 'agam-kuan', categoryId: 'heritage', name: 'Agam Kuan', src: 'https://imgs.search.brave.com/-WEwBH7ZZ2gg58odjjyFKAdPH-XQToSXbXo7NC-R4rE/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9zN2Fw/MS5zY2VuZTcuY29t/L2lzL2ltYWdlL2lu/Y3JlZGlibGVpbmRp/YS9hZ2FtLWt1YW4t/cGF0bmEtYmloYXIt/Mi1tdXN0aGVhZC1o/ZXJvP3FsdD04MiZ0/cz0xNzQyMTYyNTk1/MjMy', fact: 'Maurya-era mysterious well.' },
  { id: 'pawapuri', categoryId: 'heritage', name: 'Pawapuri Temple', src: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Mundeshwari_temple.jpg', fact: 'Place of Mahavira\'s Nirvana.' },
  { id: 'ajatshatru', categoryId: 'heritage', name: 'Ajatshatru Fort', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Telhara_Ancient_University_Excavation_Site.jpg', fact: 'Ancient fortification area.' },
  { id: 'vidhan-sabha', categoryId: 'modern', name: 'Vidhan Sabha', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Bihar_Vidhan_Sabha_Building.jpg', fact: 'Democracy focal point.' },
  { id: 'high-court', categoryId: 'modern', name: 'Patna High Court', src: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Patna_High_Court_building.jpg', fact: 'Seat of judgment in Bihar.' },
  { id: 'nalanda-new', categoryId: 'modern', name: 'Nalanda New Campus', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Telhara_Ancient_University_Excavation_Site.jpg', fact: 'Modern rebirth of Nalanda.' },
  { id: 'rajendra-setu', categoryId: 'modern', name: 'Rajendra Setu', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rajendra_Setu.jpg/1280px-Rajendra_Setu.jpg', fact: 'First Ganges bridge.' },
  { id: 'gaya-airport', categoryId: 'modern', name: 'Gaya Airport', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/IIT_Patna_Campus.jpg/1280px-IIT_Patna_Campus.jpg', fact: 'International gateway for pilgrims.' },
  { id: 'makhana-kheer', categoryId: 'food', name: 'Makhana Kheer', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Makhana_Kheer.jpg/1280px-Makhana_Kheer.jpg', fact: 'Sweet dish made of fox nuts.' },
  { id: 'bihari-kebab', categoryId: 'food', name: 'Bihari Kebab', src: 'https://thumbs.dreamstime.com/b/champaran-mutton-handi-ahuna-popular-dish-bihar-state-india-253105610.jpg', fact: 'Soft-marinated spicy skewers.' },
  { id: 'fish-curry', categoryId: 'food', name: 'Bihari Fish Curry', src: 'https://imgs.search.brave.com/FjyE0J4Kr8Oq_trm3FdKPms2k8Nuv8O5To8wdA2xsWo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9saXR0/aS1jaG9raGEtbGl0/aS1jaG9rYS1zdHVm/ZmVkLWNoYW5hLXNh/dHR1LWluZGlhbi1k/aXNoLWJpaGFyLXNl/cnZlZC1naW5nZXIt/Z2FybGljLW1pbnQt/Y2h1dG5leS1iYWlu/Z2FuLTIxNjg5MjM4/OS5qcGc', fact: 'Mustard-based traditional preparation.' },
  { id: 'aloo-chana', categoryId: 'food', name: 'Aloo Chana Curry', src: 'https://imgs.search.brave.com/Cf8e3M1xmkKkRdVM-1Wu9oe9A6XZLZDu98qocaf2SBU/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/dmVnYW5yaWNoYS5j/b20vd3AtY29udGVu/dC91cGxvYWRzLzIw/MjMvMDUvS2FsYS1D/aGFuYS1HaHVnbmkt/NzY0NC0zMDB4MzAw/LmpwZw', fact: 'Staple flavorful veggie curry.' },
  { id: 'chura-dahi', categoryId: 'food', name: 'Chura Dahi', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Malpua.jpg/1280px-Malpua.jpg', fact: 'Traditional breakfast pair.' },
  { id: 'chanakya', categoryId: 'culture', name: 'Chanakya', src: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Aryabhata.jpg', fact: 'The great Mauryan strategist.' },
  { id: 'aryabhatta', categoryId: 'culture', name: 'Aryabhatta', src: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Aryabhata.jpg', fact: 'Inventor of Zero from Bihar.' },
  { id: 'dashrath', categoryId: 'culture', name: 'Dashrath Manjhi', src: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Dashrath_Manjhi.jpg', fact: 'Famous mountain carver.' },
  { id: 'magadh', categoryId: 'culture', name: 'Magadh History', src: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Didarganj_Yakshi_Patna_Museum.jpg', fact: 'Imperial glory of ancient India.' },
  { id: 'jain-buddha', categoryId: 'culture', name: 'Buddhism Traditions', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Buddha_Statue_in_Bodh_Gaya.jpg', fact: 'Roots of world religions in Bihar.' },

  // --- 55+ YEARS ---
  { id: 'lauria', categoryId: 'heritage', name: 'Lauria Nandangarh', src: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Ashoka%27s_Pillar%2C_Vaishali.jpg', fact: 'Maurya Ashokan pillar site.' },
  { id: 'mundeshwari', categoryId: 'heritage', name: 'Mundeshwari Temple', src: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Mundeshwari_temple.jpg', fact: 'Oldest functional Hindu temple.' },
  { id: 'v-ruins', categoryId: 'heritage', name: 'Vikramshila Ruins', src: 'https://imgs.search.brave.com/ooqCkiQL_csUSkctKBeRQm6F50ADCTg-4rsxa9bEJ7s/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly9oaXN0/b3JpZmllZC5pbi93/cC1jb250ZW50L3Vw/bG9hZHMvMjAyMi8w/NS9TY3JlZW5zaG90/XzIwMjAwNTMxLTE1/MzUzNi03MjB4NTYw/LmpwZw', fact: 'Deep monastic university remains.' },
  { id: 'layout', categoryId: 'heritage', name: 'Old Nalanda Layout', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Telhara_Ancient_University_Excavation_Site.jpg', fact: 'Ancient archaeological grid.' },
  { id: 'telhara', categoryId: 'heritage', name: 'Telhara University', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Telhara_Ancient_University_Excavation_Site.jpg', fact: 'Excavated ancient education site.' },
  { id: 'old-patna', categoryId: 'modern', name: 'Old Patna City', src: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Patna_Museum_%28cropped%29.jpg', fact: 'Heritage architecture of old town.' },
  { id: 'sonpur-jnc', categoryId: 'modern', name: 'Sonpur Junction', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/IIT_Patna_Campus.jpg/1280px-IIT_Patna_Campus.jpg', fact: 'Historic railway hub.' },
  { id: 'barauni', categoryId: 'modern', name: 'Barauni Refinery', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rajendra_Setu.jpg/1280px-Rajendra_Setu.jpg', fact: 'Pillar of Bihar industry.' },
  { id: 'hajipur', categoryId: 'modern', name: 'Hajipur Industrial', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rajendra_Setu.jpg/1280px-Rajendra_Setu.jpg', fact: 'Industrial development zone.' },
  { id: 'haats', categoryId: 'modern', name: 'Traditional Haats', src: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rural_Bihar.jpg', fact: 'Classic village marketplaces.' },
  { id: 'malpua', categoryId: 'food', name: 'Malpua', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Malpua.jpg/1280px-Malpua.jpg', fact: 'Bihar\'s own sweet pancakes.' },
  { id: 'gur-sweets', categoryId: 'food', name: 'Gur Sweets', src: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Malpua.jpg/1280px-Malpua.jpg', fact: 'Jaggery-based healthy desserts.' },
  { id: 'khichdi', categoryId: 'food', name: 'Traditional Khichdi', src: 'https://imgs.search.brave.com/FjyE0J4Kr8Oq_trm3FdKPms2k8Nuv8O5To8wdA2xsWo/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly90aHVt/YnMuZHJlYW1zdGlt/ZS5jb20vYi9saXR0/aS1jaG9raGEtbGl0/aS1jaG9rYS1zdHVm/ZmVkLWNoYW5hLXNh/dHR1LWluZGlhbi1k/aXNoLWJpaGFyLXNl/cnZlZC1naW5nZXIt/Z2FybGljLW1pbnQt/Y2h1dG5leS1iYWlu/Z2FuLTIxNjg5MjM4/OS5qcGc', fact: 'Bihar Saturday special meal.' },
  { id: 'saag-bhaat', categoryId: 'food', name: 'Saag Bhaat', src: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Rural_Bihar.jpg', fact: 'Classic rural nutritional meal.' },
  { id: 'handia', categoryId: 'food', name: 'Local Drinks', src: 'https://imgs.search.brave.com/6qxhZBEGvpA7KlMwTmbeO9UFKlgfGp8QLzjxpvJBwXY/rs:fit:500:0:1:0/g:ce/aHR0cHM6Ly93d3cu/c2h1dHRlcnN0b2Nr/LmNvbS9pbWFnZS1w/aG90by9zYXR0dS1z/dW1tZXItZHJpbmst/cHJlcGFyZWQtYnkt/MjYwbnctMTM2NTI5/MDQ5NS5qcGc', fact: 'Traditional fermented beverages.' },
  { id: 'angika', categoryId: 'culture', name: 'Angika Culture', src: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Didarganj_Yakshi_Patna_Museum.jpg', fact: 'Roots of Anga region heritage.' },
  { id: 'magahi', categoryId: 'culture', name: 'Magahi Traditions', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Bihar_Focal_Dance-.jpg', fact: 'Language and customs of Magadh.' },
  { id: 'mauryan-e', categoryId: 'culture', name: 'Mauryan Empire', src: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Didarganj_Yakshi_Patna_Museum.jpg', fact: 'Golden era of Bihar\'s past.' },
  { id: 'gupta-e', categoryId: 'culture', name: 'Gupta Empire', src: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Didarganj_Yakshi_Patna_Museum.jpg', fact: 'Era of science and mathematics.' },
  { id: 'buddhist-c', categoryId: 'culture', name: 'Buddhist Circuits', src: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Buddha_Statue_in_Bodh_Gaya.jpg', fact: 'Deep holy exploration routes.' }
];

export const AGE_GROUPS = {
  under_15: { id: 'under_15', size: 3, label: 'Under 15', tag: '🧒 Young Minds', allowedImages: ['mahabodhi', 'nalanda-u', 'golghar', 'buddha-statue', 'rajgir-hills', 'patna-metro', 'gandhi-maidan', 'ecopark', 'ganga-riverfront', 'jp-path', 'litti-chokha', 'sattu-drink', 'thekua', 'khaja', 'chana-ghugni', 'madhubani', 'chhath', 'folk-dance', 'ganga-aarti', 'village-life'] },
  age_16_30: { id: 'age_16_30', size: 3, label: '16-30 Years', tag: '⚡ Youth', allowedImages: ['barabar-caves', 'sher-shah-tomb', 'ashoka-pillar', 'rajgir-ropeway', 'kesaria-stupa', 'iit-patna', 'nit-patna', 'aiims-patna', 'patna-museum', 'bihar-museum', 'sattu-paratha', 'dal-pitha', 'champaran-mutton', 'kadhi-bari', 'tilkut', 'sonepur-mela', 'shrawani-mela', 'mithila-art', 'bhojpuri-songs', 'bidesia'] },
  age_30_55: { id: 'age_30_55', size: 3, label: '30-55 Years', tag: '🌟 Adults', allowedImages: ['vikramshila-u', 'rohtasgarh', 'agam-kuan', 'pawapuri', 'ajatshatru', 'vidhan-sabha', 'high-court', 'nalanda-new', 'rajendra-setu', 'gaya-airport', 'makhana-kheer', 'bihari-kebab', 'fish-curry', 'aloo-chana', 'chura-dahi', 'chanakya', 'aryabhatta', 'dashrath', 'magadh', 'jain-buddha'] },
  age_55_plus: { id: 'age_55_plus', size: 3, label: '55+ Years', tag: '🧠 Seniors', allowedImages: ['lauria', 'mundeshwari', 'v-ruins', 'layout', 'telhara', 'old-patna', 'sonpur-jnc', 'barauni', 'hajipur', 'haats', 'malpua', 'gur-sweets', 'khichdi', 'saag-bhaat', 'handia', 'angika', 'magahi', 'mauryan-e', 'gupta-e', 'buddhist-c'] }
};

export const LS_KEYS = { bestScore: 'bihar-puzzle-best-score' };
export const GAME_MODES = { SLIDER: 'slider', DRAG_DROP: 'drag_drop', JIGSAW: 'jigsaw' };
